# Generated by Django 2.2.10 on 2021-01-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210127_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_bool',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(blank=True),
        ),
    ]
