# Generated by Django 2.2.10 on 2021-01-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210127_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_bool',
        ),
    ]
