# Generated by Django 2.2.10 on 2021-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_choice_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.CharField(max_length=255),
        ),
    ]
