# Generated by Django 2.2.10 on 2021-01-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210127_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
